#!/bin/bash 
declare -a cydia cydia=($CYDIA)
echo "正在备份表情"
cp -a /System/Library/Fonts/Core/AppleColorEmoji@2x.ttc* /var/mobile/Documents/emoji/bak/
echo "备份表情结束"
echo "正在替换表情"
mv /var/mobile/Documents/emoji/Core/* /System/Library/Fonts/Core/
echo "替换表情成功"

echo "清理缓存"
rm -rf /var/mobile/Library/Caches/com.apple.UIStatusBar
rm -rf /var/mobile/Library/Caches/com.apple.keyboards
echo "清理成功"

echo "Acreson源 ：https://crazyc.top"
echo "祝您越狱愉快"
if [[ ${CYDIA+@} ]]; then
        eval "echo 'finish:restart' >&${cydia[0]}"
fi
exit 0