#!/bin/bash

model=`/Library/dpkg/info/com.michael.appleturboboost.uname -i`

#Setting WatchDog plist file
watchdog_plist="/System/Library/Watchdog/ThermalMonitor.bundle/${model}.bundle/Info.plist"

#If can’t find WatchDog plist file, return exit 1
if [[ ! -f "${watchdog_plist}" ]];then
	echo "Error: Couldn't find the WatchDog properties plist (${watchdog_plist})"
	exit 1
fi

#Backup orig WatchDog plist file
cp -a "${watchdog_plist}" "${watchdog_plist}.bak"
echo "Created the backup file (${watchdog_plist}.bak)"

#Start Apple Trubo Boost!!!
for subitem in `plutil -key thermalMitigationLimits -key light $watchdog_plist`
do
	if [[ ! $subitem == "=" && ! $subitem == *\; && ! $subitem == \{ && ! $subitem == \} && ! $subitem == description ]];then
		ture_subitem=`echo $subitem | sed 's/\"//g'`
		for item in heavy moderate
		do
			if [[ `plutil -key thermalMitigationLimits -key $item -key $ture_subitem $watchdog_plist` ]];then
				plutil -key thermalMitigationLimits -key $item -key $ture_subitem -int `plutil -key thermalMitigationLimits -key light -key $ture_subitem $watchdog_plist` $watchdog_plist
			fi
		done
	fi
done
plutil -key contextualClampParams -key lowParamsPeakPower -remove $watchdog_plist
plutil -key contextualClampParams -key lowParamsSpeaker -remove $watchdog_plist

for item in {0..15}
do
	for subitem in `plutil -key hotspots -key $item $watchdog_plist`
	do
		if [[ ! $subitem == "=" && ! $subitem == *\; && ! $subitem == \{ && ! $subitem == \} && ! $subitem == description ]];then
ture_subitem=`echo $subitem | sed 's/\"//g'`
			if [[ `plutil -key hotspots -key $item -key $ture_subitem $watchdog_plist` ]];then
				plutil -key hotspots -key $item -key $ture_subitem -remove $watchdog_plist
			fi
		fi
	done
done

for item in {1..3}
do
	plutil -key backlightComponentControl -key BacklightBrightness -key $item -key down -int `plutil -key backlightComponentControl -key BacklightBrightness -key 0 -key down $watchdog_plist` $watchdog_plist
	plutil -key backlightComponentControl -key BacklightBrightness -key $item -key level -int `plutil -key backlightComponentControl -key BacklightBrightness -key 0 -key level $watchdog_plist` $watchdog_plist
	plutil -key backlightComponentControl -key BacklightBrightness -key $item -key up -int `plutil -key backlightComponentControl -key BacklightBrightness -key 0 -key up $watchdog_plist` $watchdog_plist
done

if [[ $1 == install || $1 == upgrade ]];then
	echo "Everything Done! You need a reboot to Turbo Boost your Apple!"
	function finish() {
		f="${1}"
		[[ -z "${f}" || -z "${CYDIA}" ]] && return
		cydia=(${CYDIA})
		[[ ${cydia[1]} -eq 1 ]] || return
		echo "finish:${f}" >&${cydia[0]}
	}
    finish reboot
fi
